[package]
name = "i8254_pit"
version = "0.1.0"
edition.workspace = true
authors = ["Axvisor Team"]
description = "Intel 8254 PIT (Programmable Interval Timer) emulation"
license = "Apache-2.0"

[dependencies]
log = "0.4"
ax-errno = { workspace = true }
axaddrspace = { workspace = true }
axdevice_base = { workspace = true }
axvisor_api = { workspace = true }
spin = { workspace = true }