uefi = false
args = [
  "-nographic",
  "-cpu", "host",
  "-machine", "q35",
  "-smp", "4",
  "-enable-kvm",
  "-device", "virtio-blk-pci,drive=disk0",
  "-drive", "id=disk0,if=none,format=raw,file=${workspace}/tmp/axbuild/rootfs/rootfs-x86_64-alpine.img",
  "-m", "4G",
]
fail_regex = ["ASSERT", "PANIC"]
success_regex = []
to_bin = false